mod triangle;
pub use triangle::TriangleWave;
mod square;
pub use square::SquareWave;
mod sawtooth;
pub use sawtooth::SawToothWave;
mod source_wrapper;
pub use source_wrapper::{AsGenericSource, GenericSource};
mod lfo;
pub use lfo::{Lfo, SourceToLfo};
mod impls;
use impls::*;
