mod impls;
mod triangle;
pub use triangle::TriangleWave;
mod square;
pub use square::SquareWave;
mod sawtooth;
pub use sawtooth::SawToothWave;
mod lfo;
pub use lfo::Lfo;
mod cloneable_decoder;
pub use cloneable_decoder::CloneableDecoder;
mod clamp;
pub use clamp::Clamp;
mod abs;
pub use abs::Abs;
mod noise;
pub use noise::Noise;
mod merge_channels;
pub use merge_channels::MergeChannels;
mod split_channels;
pub use split_channels::SplitChannels;
mod pop;
pub use pop::Pop;
mod mod_source;
pub use mod_source::Mod;
mod automated_sawtooth;
pub use automated_sawtooth::AutomatedSawToothWave;
mod pitch_shifter;
mod translate_wave;
pub use translate_wave::TranslateWave;
mod automated_sine;
pub use automated_sine::AutomatedSineWave;
mod automated_square;
pub use automated_square::AutomatedSquareWave;
mod signum;
pub use signum::Signum;
mod automated_triangle;
pub use automated_triangle::AutomatedTriangleWave;
mod automated_mod;
pub use automated_mod::AutomatedMod;
