[package]
name = "node_sound"
version = "0.1.0"
authors = ["Lubba64"]
edition = "2021"
rust-version = "1.56"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.17.3"
eframe = "0.18.0"
egui_node_graph = "0.3.0"
dyn-clone = "1.0.17"
