[package]
name = "node_sound_app"
version = "1.3.2"
edition = "2021"

[dependencies]
eframe = "0.27.2"
node_sound_core = { version = "*", path = "../node_sound_core", default-features = false, features = ["non-wasm"]}
