[package]
name = "node_sound_app"
version =  "1.6.1"
edition = "2021"

[dependencies]
eframe = "0.27.2"
node_sound_core = { version = "*", path = "../node_sound_core", default-features = false }
wasm-bindgen-futures = "0.4.42"
