[package]
name = "node_sound_app"
version =  "1.10.2"
edition = "2021"

[dependencies]
eframe = "^0.31"
node_sound_core = { version = "*", path = "../node_sound_core", default-features = false }
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3.69", features = ["Clipboard", "Navigator"] }
