[package]
name = "node_sound_vst"
version = "1.2.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug ={version = "0.0.0", git = "https://github.com/robbert-vdh/nih-plug.git"}
node_sound_core ={version = "*", path = "../node_sound_core"}
nih_plug_egui ={version = "0.0.0", git = "https://github.com/robbert-vdh/nih-plug.git"}
